quarkus.application.name=UWSServer

# registry/resource related
ivoa.baseAddress=http://localhost:8080/
ivoa.registry.authority=authority.changeme
ivoa.dc.organizationName=Organization
ivoa.dc.contactName=Contact Name
ivoa.dc.contactAddress=Contact Address
ivoa.dc.contactEmail=Contact E-mail.
ivoa.dc.contactTelephone=Contact Telephone number


#image build
quarkus.container-image.builder=docker
quarkus.container-image.name=uws-server
quarkus.container-image.group=javastro
quarkus.container-image.tag=latest
